apiVersion: v1
kind: Config
clusters:
- name: "staging-docker"
  cluster:
    server: "https://172.16.4.181/k8s/clusters/c-sncfj"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM3akNDQ\
      WRhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFvTVJJd0VBWURWUVFLRXdsMGFHVXQKY\
      21GdVkyZ3hFakFRQmdOVkJBTVRDV05oZEhSc1pTMWpZVEFlRncweU1EQXlNVGd3TXpVME5USmFGd\
      zB6TURBeQpNVFV3TXpVME5USmFNQ2d4RWpBUUJnTlZCQW9UQ1hSb1pTMXlZVzVqYURFU01CQUdBM\
      VVFQXhNSlkyRjBkR3hsCkxXTmhNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ\
      0tDQVFFQXZncTY4RWd3VjFtaVZueVIKR2FCMFlPNXdQVEd3TnlxMU5rb216SjZqZkZidDNSMHo2a\
      GtRNTVaWFd2c1pJTXhCRVVQVWxrMmlTeUlmUXJmdwplUU9xZzFINlIwa1p5MFMwbHNER1NlS25EW\
      mhjMk1RQ2w1Y1dXSG0rVThaOEJUQWt0Z2ltU3kvUTd0eXVzbXRRCmJiVG1ENTlyNCtLWE9aSmRQK\
      2VWcER3TEpLYjlZOXFSd21Ca09lSWt4VGFEdFNkUXhldmlhODlxdCsxNEREblIKU3kyZVJCMWtJb\
      HBXbTVZYnRJUnBLdzAxbDBlY2FZa0p2Z3I5dVY4VFVKVWg2K3FhdlYrazF5a2NKWDZHTnR1VQo2W\
      UN0T3pLZUkwbmNKQUpUZ1dFZ01CMnpyMUZZeVFqUU02ZjVlTDJZcXRIVjd6RERaRms3SFowS2ZkY\
      UZhMFg0CnFjQm9kUUlEQVFBQm95TXdJVEFPQmdOVkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRS\
      C9CQVV3QXdFQi96QU4KQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBSGlpY1Y2Ym8zSmc5TmkvaG9vc\
      HNzZUVEcit3THo3bTQvM2V0MmFGcQp6MnJ1MUdZcUcxUkl4UGk5SVJxVkpOdFFBNXJCS2lRN2dNU\
      i9GdUhzQkdQYm8vaGRKUkp6d24yMjMzRW1VM1pKCmtON3RhKzVrZmM4RUFIMzlGNmF3T2o1aDM2W\
      TRCQVVBUTlDS2Z1VDRTa3BLTmdTa2krRTBteDNqK3FCOWRramIKQkhHMHMwcmFkU0UwN2Q5em0wW\
      lEwNy92VEh5dHdCRGFneC9BdEVvb2hET2U1cGlRS2kyeHZYR1BiNGVQNDJuZAp2TTVCNjdpK2pyd\
      kdzUHM5UlB4eVh5bDVVeFZpV29YMVdnTVRVTWJJQWY3cUN3YnNHWlkrR3c0ckoxc0JzcDlmClFMW\
      kN6TjdzdGZrckhWKzRWMUFtSmxMa1A1QzhtbUgzMlluUklRTW1aNVNKamc9PQotLS0tLUVORCBDR\
      VJUSUZJQ0FURS0tLS0t"
- name: "staging-docker-vStaging-Rancher02"
  cluster:
    server: "https://172.16.4.182:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURJeE9EQTBNRFUwTVZvWERUTXdNREl4TlRBME1EVTBNVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU1yRmMvTm4wYk5LCjZBVnhoMGd3aXVCRkUrckswbHRnTHZqeEExRTJGN3ZkWWp6V0NPcW94Z\
      DVxREU3Sk9qRWZMNFQyS0oxbEczc3UKWWx1VlY2ajBqK21kYzF6TzlWUXlmd2dUdlZSUVRFSGt2V\
      lF5ajdteTMzRmE0MEQzU3FWTDFKT2lzWnFoZUlFRwo4NjViQ1llS25Dci9BajFENkI0MnhFR3lId\
      jhwT1JUdzFSb0xxczZ4MkV1SHFNUEJHWkJpQ2xUVTZ0aVdyT3J3Cnk0amVvVjBBcXU2WVFTZ3JjR\
      0F3a2JyU3F0by96Yk1HMlV5NnlLdGQ5ZzNjQ1BEVVF5VWpqdUVLT2xBMkF6NFEKQWV5REMweHNwV\
      VB1eC9KenpqNzByVlJMYklrM3FNY1lGc2JVejNXb2swWE5FSGlqa29GUzBkeTRNaXdXanpOcQpPS\
      VlYZkdaVlJUVUNBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQStLK2JXWGlXanQzUFBtZlpMd1A5M\
      GovR0EzckZHaUFRNHkKYTd3dnRjWjlRYlI1ckxmYmNORGVzMFllTWE0dDU0d080QXYreXlOZi85c\
      U9tTWZNU2c3SGdtL3FaWGVyaDc4WQp2VVlUaFNhOWErTHpabThaaCtZVTNBWnp6UzRhVGJybjRrZ\
      UlUODJVVFpFK3phS2VNekgyaVAvekdZRmlwVlRqCkVCd0FJZncwZXk3VTY4MFlSbUNXUHFEZ1E2R\
      lovellTZHI4YWNWYkZpaE1Bd0lMTGViU2JsRWd1c244K3hkNGIKTTJhSC9yNXlESkRJdnRjVXRSQ\
      1NrNHJieFBxays0ZlJwTHhPQURmT2s2K09mdnBqeHkrMXNNeU1LYnkrWTRRNgovS0l5TkZCUlk1S\
      mw2b2NpMy9vZHVOazR5N05LTExFTng2ems5TVRHR2lHQ1dGV05DL0U9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "staging-docker-vStaging-Rancher01"
  cluster:
    server: "https://172.16.4.181:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURJeE9EQTBNRFUwTVZvWERUTXdNREl4TlRBME1EVTBNVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU1yRmMvTm4wYk5LCjZBVnhoMGd3aXVCRkUrckswbHRnTHZqeEExRTJGN3ZkWWp6V0NPcW94Z\
      DVxREU3Sk9qRWZMNFQyS0oxbEczc3UKWWx1VlY2ajBqK21kYzF6TzlWUXlmd2dUdlZSUVRFSGt2V\
      lF5ajdteTMzRmE0MEQzU3FWTDFKT2lzWnFoZUlFRwo4NjViQ1llS25Dci9BajFENkI0MnhFR3lId\
      jhwT1JUdzFSb0xxczZ4MkV1SHFNUEJHWkJpQ2xUVTZ0aVdyT3J3Cnk0amVvVjBBcXU2WVFTZ3JjR\
      0F3a2JyU3F0by96Yk1HMlV5NnlLdGQ5ZzNjQ1BEVVF5VWpqdUVLT2xBMkF6NFEKQWV5REMweHNwV\
      VB1eC9KenpqNzByVlJMYklrM3FNY1lGc2JVejNXb2swWE5FSGlqa29GUzBkeTRNaXdXanpOcQpPS\
      VlYZkdaVlJUVUNBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQStLK2JXWGlXanQzUFBtZlpMd1A5M\
      GovR0EzckZHaUFRNHkKYTd3dnRjWjlRYlI1ckxmYmNORGVzMFllTWE0dDU0d080QXYreXlOZi85c\
      U9tTWZNU2c3SGdtL3FaWGVyaDc4WQp2VVlUaFNhOWErTHpabThaaCtZVTNBWnp6UzRhVGJybjRrZ\
      UlUODJVVFpFK3phS2VNekgyaVAvekdZRmlwVlRqCkVCd0FJZncwZXk3VTY4MFlSbUNXUHFEZ1E2R\
      lovellTZHI4YWNWYkZpaE1Bd0lMTGViU2JsRWd1c244K3hkNGIKTTJhSC9yNXlESkRJdnRjVXRSQ\
      1NrNHJieFBxays0ZlJwTHhPQURmT2s2K09mdnBqeHkrMXNNeU1LYnkrWTRRNgovS0l5TkZCUlk1S\
      mw2b2NpMy9vZHVOazR5N05LTExFTng2ems5TVRHR2lHQ1dGV05DL0U9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"

users:
- name: "staging-docker"
  user:
    token: "kubeconfig-u-bfj2x.c-sncfj:9lv6vtwzwvpqhnzw8l4kddkn57dmf7b4n8dp4q4mgbhdbzh8hbz5v8"

contexts:
- name: "staging-docker"
  context:
    user: "staging-docker"
    cluster: "staging-docker"
- name: "staging-docker-vStaging-Rancher02"
  context:
    user: "staging-docker"
    cluster: "staging-docker-vStaging-Rancher02"
- name: "staging-docker-vStaging-Rancher01"
  context:
    user: "staging-docker"
    cluster: "staging-docker-vStaging-Rancher01"

current-context: "staging-docker-vStaging-Rancher01"