Vagrant.configure("2") do |config|

  # Cài đặt box cho máy ảo
  config.vm.box = "ubuntu/bionic64"

  # Cấu hình cho máy ảo 192.168.144.10
  config.vm.define "machine1" do |machine1|
    machine1.vm.network "private_network", ip: "192.168.144.10"
    machine1.vm.hostname = "machine1"

    # Chạy script shell từ file bên ngoài
    machine1.vm.provision "shell", path: "./shellscript/setup_users1.sh"
  end

  # Cấu hình cho máy ảo 192.168.144.11
  config.vm.define "machine2" do |machine2|
    machine2.vm.network "private_network", ip: "192.168.144.11"
    machine2.vm.hostname = "machine2"

    # Chạy script shell từ file bên ngoài
    machine2.vm.provision "shell", path: "./shellscript/setup_users2.sh"
  end

  # Cấu hình tài nguyên cho máy ảo
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
end
