- hosts: "{{ env_name }}"
  become: yes
  tasks:
    - name: Copy file crm-sync-application.sh
      copy:
        src: template/crm-sync-application.sh
        dest: /usr/lib64/nagios/plugins/crm-sync-application.sh
        mode: +x

    - name: remove old nrpe command
      ansible.builtin.lineinfile:
        path: /etc/nagios/nrpe.cfg
        state: absent
        regexp: '^.*check_crm-sync-application.sh'

    - name: Add nrpe commmand
      ansible.builtin.lineinfile:
        path: /etc/nrpe.d/command.cfg
        regexp: '^.*check_crm-sync-application.sh'
        line: command[check_crm_sync_application=/usr/lib64/nagios/plugins/crm-sync-application.sh
        create: yes

    - name: Reload service nrpe
      ansible.builtin.service:
        name: nrpe
        state: reloaded