version: "3.7"

services:
  samba:
    image: dangnk/samba
    ports:
      - 139:139
      - 445:445
    environment:
      smbuser: smbuser
      password: 1234567
    volumes:
      - /home/:/data/
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager

  services1:
    image: dangnk/swarmtest:node0
    networks:
      - net1
    volumes:
      - vol1:/d1/
      - vol2:/d2/
    ports:
      - 8086:8085
    
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        # reservations:
        #   cpus: '0.25'
        #   memory: 50MB
      restart_policy:
        condition: on-failure

  services2:
    image: dangnk/swarmtest:node1
    networks:
      - net2
    volumes:
      - vol1:/d1/
      - vol2:/d2/
    ports:
      - 8087:8085
    
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        # reservations:
        #   cpus: '0.25'
        #   memory: 50MB
      restart_policy:
        condition: on-failure

networks:
  net1:
  net2:
    driver: overlay
    name: www-net2

volumes:
  vol1:
    driver: local
    name: v1
    driver_opts:
      type: none
      device: "/home/"
      o: bind
    
  vol2:
    driver: local
    name: v2
    driver_opts:
      type: cifs
      device: //192.168.63.100/data
      o: "username=smbuser,password=1234567,file_mode=0777,dir_mode=0777"
  
