apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-sync-master
  namespace: webapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 5Gi