apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        type: deployment
        app: db
    spec:
      containers:
      - image: postgres:10
        imagePullPolicy: IfNotPresent
        name: db
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: db-config
        volumeMounts:
          - name: dbmnt
            mountPath: /var/lib/postgresql/data
            subPath: db/data
      volumes:
      - name: dbmnt
        persistentVolumeClaim:
          claimName: nfs
      - name: db-conf-files-config-mnt
        configMap:
          name: db-conf-files-config
      initContainers:
      - name: init-db
        image: busybox:1.28
        command: ['sh', '-c', ' cp /var/lib/postgresql/data/postgresql.main.conf /var/lib/postgresql/data/postgresql.conf && cp /var/lib/postgresql/data/pg_hba.main.conf /var/lib/postgresql/data/pg_hba.conf && chmod 600 /var/lib/postgresql/data/postgresql.conf && chmod 600 /var/lib/postgresql/data/pg_hba.conf']
        volumeMounts:
        - name: dbmnt
          mountPath: /var/lib/postgresql/data
          subPath: db/data
        - name: db-conf-files-config-mnt
          mountPath: /var/lib/postgresql/data/postgresql.main.conf
          subPath: postgresql.conf
        - name: db-conf-files-config-mnt
          mountPath: /var/lib/postgresql/data/pg_hba.main.conf
          subPath: pg_hba.conf            


---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: NodePort
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

