apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: webapp
spec:
  storageClassName: mystorageclass
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/webapp"  # Specify the host directory where the data will be stored
