apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-slave
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-slave
  template:
    metadata:
      labels:
        app: postgresql-slave
    spec:
      containers:
      - name: postgresql-slave
        image: bitnami/postgresql
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_REPLICATION_MODE
          value: slave
        - name: POSTGRESQL_REPLICATION_USER
          value: repl_user
        - name: POSTGRESQL_REPLICATION_PASSWORD
          value: repl_password
        - name: POSTGRESQL_MASTER_HOST
          value: "0.0.0.0"
        - name: POSTGRESQL_PASSWORD
          value: my_password
        - name: POSTGRESQL_MASTER_PORT_NUMBER
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: webapp
spec:
  selector:
    app: postgresql-master
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
