- name: Install k8s v2
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - curl
        - ca-certificates
        - software-properties-common

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      changed_when: false

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
      changed_when: false

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      changed_when: false

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      changed_when: false

    - name: Configure containerd
      file:
        path: /etc/containerd/config.toml
        state: touch
      changed_when: false

    - name: Set SystemdCgroup to false in containerd config
      lineinfile:
        path: /etc/containerd/config.toml
        line: "SystemdCgroup = false"
      changed_when: false

    - name: Restart containerd service
      service:
        name: containerd
        state: restarted
        enabled: yes
      changed_when: false

    - name: Add Kubernetes GPG key
      shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      changed_when: false

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
      changed_when: false

    - name: Install Kubernetes packages
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
          - kubernetes-cni
        state: present
      changed_when: false

    - name: Disable swap
      command: swapoff -a
      ignore_errors: true
      changed_when: false

    - name: Update sysctl settings
      sysctl:
        name: "{{ item }}"
        value: "1"
        sysctl_set: yes
        state: present
      with_items:
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
      changed_when: false
